# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Documents/Fontys/ES/adv_emb/git/floaty-wiggle-board/Floaty-wiggle-board/Floaty-wiggle-board.srcs/sources_1/bd/Floaty_board_design/ip/Floaty_board_design_xbar_0/Floaty_board_design_xbar_0.xci
# IP: The module: 'Floaty_board_design_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/Fontys/ES/adv_emb/git/floaty-wiggle-board/Floaty-wiggle-board/Floaty-wiggle-board.srcs/sources_1/bd/Floaty_board_design/ip/Floaty_board_design_xbar_0/Floaty_board_design_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Floaty_board_design_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/Documents/Fontys/ES/adv_emb/git/floaty-wiggle-board/Floaty-wiggle-board/Floaty-wiggle-board.srcs/sources_1/bd/Floaty_board_design/ip/Floaty_board_design_xbar_0/Floaty_board_design_xbar_0.xci
# IP: The module: 'Floaty_board_design_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/Fontys/ES/adv_emb/git/floaty-wiggle-board/Floaty-wiggle-board/Floaty-wiggle-board.srcs/sources_1/bd/Floaty_board_design/ip/Floaty_board_design_xbar_0/Floaty_board_design_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Floaty_board_design_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
