# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Floaty_board_design/Floaty_board_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Floaty_board_design || ORIG_REF_NAME==Floaty_board_design} -quiet] -quiet

# IP: bd/Floaty_board_design/ip/Floaty_board_design_processing_system7_0_0/Floaty_board_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Floaty_board_design_processing_system7_0_0 || ORIG_REF_NAME==Floaty_board_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/Floaty_board_design/ip/Floaty_board_design_axi_timer_0_0/Floaty_board_design_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Floaty_board_design_axi_timer_0_0 || ORIG_REF_NAME==Floaty_board_design_axi_timer_0_0} -quiet] -quiet

# IP: bd/Floaty_board_design/ip/Floaty_board_design_ps7_0_axi_periph_0/Floaty_board_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Floaty_board_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==Floaty_board_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Floaty_board_design/ip/Floaty_board_design_rst_ps7_0_50M_0/Floaty_board_design_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Floaty_board_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==Floaty_board_design_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/Floaty_board_design/ip/Floaty_board_design_axi_gpio_0_0/Floaty_board_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Floaty_board_design_axi_gpio_0_0 || ORIG_REF_NAME==Floaty_board_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Floaty_board_design/ip/Floaty_board_design_axi_gpio_1_0/Floaty_board_design_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Floaty_board_design_axi_gpio_1_0 || ORIG_REF_NAME==Floaty_board_design_axi_gpio_1_0} -quiet] -quiet

# IP: bd/Floaty_board_design/ip/Floaty_board_design_xbar_0/Floaty_board_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Floaty_board_design_xbar_0 || ORIG_REF_NAME==Floaty_board_design_xbar_0} -quiet] -quiet

# IP: bd/Floaty_board_design/ip/Floaty_board_design_axi_iic_0_0/Floaty_board_design_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Floaty_board_design_axi_iic_0_0 || ORIG_REF_NAME==Floaty_board_design_axi_iic_0_0} -quiet] -quiet

# IP: bd/Floaty_board_design/ip/Floaty_board_design_auto_pc_0/Floaty_board_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Floaty_board_design_auto_pc_0 || ORIG_REF_NAME==Floaty_board_design_auto_pc_0} -quiet] -quiet

# XDC: bd/Floaty_board_design/Floaty_board_design_ooc.xdc
